spring.application.name=inventory

# Kafka producer configuration for inventory module
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka bootstrap servers (provide via env or override here)
spring.kafka.bootstrap-servers=localhost:9092

# Kafka consumer configuration for inventory module
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# If using JsonDeserializer with specific type, trust packages or set default type/class
spring.kafka.consumer.properties.spring.json.trusted.packages=*

