#!/usr/bin/env bash
# Minimal script: build the known services with the Gradle `dockerBuild` task, then run docker-compose up --build
# Generated by copilot, not written by me
set -euo pipefail
trap 'echo "Error at line $LINENO while executing: $BASH_COMMAND" >&2' ERR

# Repository root (assumes script is in repo/scripts)
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SERVICES=(inventory orders palpay payments shipping)
TASK="dockerBuild"

echo "==== Building services with Gradle task '$TASK' ===="
for svc in "${SERVICES[@]}"; do
  echo
  echo "==== Building $svc with Gradle task $TASK ===="
  WRAPPER="$REPO_ROOT/$svc/gradlew"
  if [[ ! -f "$WRAPPER" ]]; then
    echo "Gradle wrapper not found for service '$svc' at $WRAPPER" >&2
    exit 2
  fi
  # Ensure wrapper is executable on Unix
  chmod +x "$WRAPPER" 2>/dev/null || true

  (cd "$REPO_ROOT/$svc" && "$WRAPPER" "$TASK")
done

echo
echo "==== Starting docker-compose ===="
docker-compose up --build

exit 0

